/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedProjectsRouteImport } from './routes/_authenticated/projects'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedTablereadProjectIdRouteImport } from './routes/_authenticated/tableread.$projectId'
import { Route as AuthenticatedStoryboardProjectIdRouteImport } from './routes/_authenticated/storyboard.$projectId'
import { Route as AuthenticatedStoryArcProjectIdRouteImport } from './routes/_authenticated/story-arc.$projectId'
import { Route as AuthenticatedScenesProjectIdRouteImport } from './routes/_authenticated/scenes.$projectId'
import { Route as AuthenticatedProjectsNewRouteImport } from './routes/_authenticated/projects.new'
import { Route as AuthenticatedPitchProjectIdRouteImport } from './routes/_authenticated/pitch.$projectId'
import { Route as AuthenticatedEditorProjectIdRouteImport } from './routes/_authenticated/editor.$projectId'
import { Route as AuthenticatedCharactersProjectIdRouteImport } from './routes/_authenticated/characters.$projectId'
import { Route as AuthenticatedArcTimelineProjectIdRouteImport } from './routes/_authenticated/arc-timeline.$projectId'

const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProjectsRoute = AuthenticatedProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTablereadProjectIdRoute =
  AuthenticatedTablereadProjectIdRouteImport.update({
    id: '/tableread/$projectId',
    path: '/tableread/$projectId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStoryboardProjectIdRoute =
  AuthenticatedStoryboardProjectIdRouteImport.update({
    id: '/storyboard/$projectId',
    path: '/storyboard/$projectId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStoryArcProjectIdRoute =
  AuthenticatedStoryArcProjectIdRouteImport.update({
    id: '/story-arc/$projectId',
    path: '/story-arc/$projectId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedScenesProjectIdRoute =
  AuthenticatedScenesProjectIdRouteImport.update({
    id: '/scenes/$projectId',
    path: '/scenes/$projectId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjectsNewRoute =
  AuthenticatedProjectsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedProjectsRoute,
  } as any)
const AuthenticatedPitchProjectIdRoute =
  AuthenticatedPitchProjectIdRouteImport.update({
    id: '/pitch/$projectId',
    path: '/pitch/$projectId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEditorProjectIdRoute =
  AuthenticatedEditorProjectIdRouteImport.update({
    id: '/editor/$projectId',
    path: '/editor/$projectId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCharactersProjectIdRoute =
  AuthenticatedCharactersProjectIdRouteImport.update({
    id: '/characters/$projectId',
    path: '/characters/$projectId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedArcTimelineProjectIdRoute =
  AuthenticatedArcTimelineProjectIdRouteImport.update({
    id: '/arc-timeline/$projectId',
    path: '/arc-timeline/$projectId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/pricing': typeof PricingRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/projects': typeof AuthenticatedProjectsRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRoute
  '/arc-timeline/$projectId': typeof AuthenticatedArcTimelineProjectIdRoute
  '/characters/$projectId': typeof AuthenticatedCharactersProjectIdRoute
  '/editor/$projectId': typeof AuthenticatedEditorProjectIdRoute
  '/pitch/$projectId': typeof AuthenticatedPitchProjectIdRoute
  '/projects/new': typeof AuthenticatedProjectsNewRoute
  '/scenes/$projectId': typeof AuthenticatedScenesProjectIdRoute
  '/story-arc/$projectId': typeof AuthenticatedStoryArcProjectIdRoute
  '/storyboard/$projectId': typeof AuthenticatedStoryboardProjectIdRoute
  '/tableread/$projectId': typeof AuthenticatedTablereadProjectIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/pricing': typeof PricingRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/projects': typeof AuthenticatedProjectsRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRoute
  '/arc-timeline/$projectId': typeof AuthenticatedArcTimelineProjectIdRoute
  '/characters/$projectId': typeof AuthenticatedCharactersProjectIdRoute
  '/editor/$projectId': typeof AuthenticatedEditorProjectIdRoute
  '/pitch/$projectId': typeof AuthenticatedPitchProjectIdRoute
  '/projects/new': typeof AuthenticatedProjectsNewRoute
  '/scenes/$projectId': typeof AuthenticatedScenesProjectIdRoute
  '/story-arc/$projectId': typeof AuthenticatedStoryArcProjectIdRoute
  '/storyboard/$projectId': typeof AuthenticatedStoryboardProjectIdRoute
  '/tableread/$projectId': typeof AuthenticatedTablereadProjectIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/pricing': typeof PricingRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/projects': typeof AuthenticatedProjectsRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/arc-timeline/$projectId': typeof AuthenticatedArcTimelineProjectIdRoute
  '/_authenticated/characters/$projectId': typeof AuthenticatedCharactersProjectIdRoute
  '/_authenticated/editor/$projectId': typeof AuthenticatedEditorProjectIdRoute
  '/_authenticated/pitch/$projectId': typeof AuthenticatedPitchProjectIdRoute
  '/_authenticated/projects/new': typeof AuthenticatedProjectsNewRoute
  '/_authenticated/scenes/$projectId': typeof AuthenticatedScenesProjectIdRoute
  '/_authenticated/story-arc/$projectId': typeof AuthenticatedStoryArcProjectIdRoute
  '/_authenticated/storyboard/$projectId': typeof AuthenticatedStoryboardProjectIdRoute
  '/_authenticated/tableread/$projectId': typeof AuthenticatedTablereadProjectIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/pricing'
    | '/dashboard'
    | '/onboarding'
    | '/projects'
    | '/settings'
    | '/arc-timeline/$projectId'
    | '/characters/$projectId'
    | '/editor/$projectId'
    | '/pitch/$projectId'
    | '/projects/new'
    | '/scenes/$projectId'
    | '/story-arc/$projectId'
    | '/storyboard/$projectId'
    | '/tableread/$projectId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/pricing'
    | '/dashboard'
    | '/onboarding'
    | '/projects'
    | '/settings'
    | '/arc-timeline/$projectId'
    | '/characters/$projectId'
    | '/editor/$projectId'
    | '/pitch/$projectId'
    | '/projects/new'
    | '/scenes/$projectId'
    | '/story-arc/$projectId'
    | '/storyboard/$projectId'
    | '/tableread/$projectId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/pricing'
    | '/_authenticated/dashboard'
    | '/_authenticated/onboarding'
    | '/_authenticated/projects'
    | '/_authenticated/settings'
    | '/_authenticated/arc-timeline/$projectId'
    | '/_authenticated/characters/$projectId'
    | '/_authenticated/editor/$projectId'
    | '/_authenticated/pitch/$projectId'
    | '/_authenticated/projects/new'
    | '/_authenticated/scenes/$projectId'
    | '/_authenticated/story-arc/$projectId'
    | '/_authenticated/storyboard/$projectId'
    | '/_authenticated/tableread/$projectId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  PricingRoute: typeof PricingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects': {
      id: '/_authenticated/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AuthenticatedProjectsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tableread/$projectId': {
      id: '/_authenticated/tableread/$projectId'
      path: '/tableread/$projectId'
      fullPath: '/tableread/$projectId'
      preLoaderRoute: typeof AuthenticatedTablereadProjectIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/storyboard/$projectId': {
      id: '/_authenticated/storyboard/$projectId'
      path: '/storyboard/$projectId'
      fullPath: '/storyboard/$projectId'
      preLoaderRoute: typeof AuthenticatedStoryboardProjectIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/story-arc/$projectId': {
      id: '/_authenticated/story-arc/$projectId'
      path: '/story-arc/$projectId'
      fullPath: '/story-arc/$projectId'
      preLoaderRoute: typeof AuthenticatedStoryArcProjectIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/scenes/$projectId': {
      id: '/_authenticated/scenes/$projectId'
      path: '/scenes/$projectId'
      fullPath: '/scenes/$projectId'
      preLoaderRoute: typeof AuthenticatedScenesProjectIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects/new': {
      id: '/_authenticated/projects/new'
      path: '/new'
      fullPath: '/projects/new'
      preLoaderRoute: typeof AuthenticatedProjectsNewRouteImport
      parentRoute: typeof AuthenticatedProjectsRoute
    }
    '/_authenticated/pitch/$projectId': {
      id: '/_authenticated/pitch/$projectId'
      path: '/pitch/$projectId'
      fullPath: '/pitch/$projectId'
      preLoaderRoute: typeof AuthenticatedPitchProjectIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/editor/$projectId': {
      id: '/_authenticated/editor/$projectId'
      path: '/editor/$projectId'
      fullPath: '/editor/$projectId'
      preLoaderRoute: typeof AuthenticatedEditorProjectIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/characters/$projectId': {
      id: '/_authenticated/characters/$projectId'
      path: '/characters/$projectId'
      fullPath: '/characters/$projectId'
      preLoaderRoute: typeof AuthenticatedCharactersProjectIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/arc-timeline/$projectId': {
      id: '/_authenticated/arc-timeline/$projectId'
      path: '/arc-timeline/$projectId'
      fullPath: '/arc-timeline/$projectId'
      preLoaderRoute: typeof AuthenticatedArcTimelineProjectIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedProjectsRouteChildren {
  AuthenticatedProjectsNewRoute: typeof AuthenticatedProjectsNewRoute
}

const AuthenticatedProjectsRouteChildren: AuthenticatedProjectsRouteChildren = {
  AuthenticatedProjectsNewRoute: AuthenticatedProjectsNewRoute,
}

const AuthenticatedProjectsRouteWithChildren =
  AuthenticatedProjectsRoute._addFileChildren(
    AuthenticatedProjectsRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedProjectsRoute: typeof AuthenticatedProjectsRouteWithChildren
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedArcTimelineProjectIdRoute: typeof AuthenticatedArcTimelineProjectIdRoute
  AuthenticatedCharactersProjectIdRoute: typeof AuthenticatedCharactersProjectIdRoute
  AuthenticatedEditorProjectIdRoute: typeof AuthenticatedEditorProjectIdRoute
  AuthenticatedPitchProjectIdRoute: typeof AuthenticatedPitchProjectIdRoute
  AuthenticatedScenesProjectIdRoute: typeof AuthenticatedScenesProjectIdRoute
  AuthenticatedStoryArcProjectIdRoute: typeof AuthenticatedStoryArcProjectIdRoute
  AuthenticatedStoryboardProjectIdRoute: typeof AuthenticatedStoryboardProjectIdRoute
  AuthenticatedTablereadProjectIdRoute: typeof AuthenticatedTablereadProjectIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedProjectsRoute: AuthenticatedProjectsRouteWithChildren,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedArcTimelineProjectIdRoute:
    AuthenticatedArcTimelineProjectIdRoute,
  AuthenticatedCharactersProjectIdRoute: AuthenticatedCharactersProjectIdRoute,
  AuthenticatedEditorProjectIdRoute: AuthenticatedEditorProjectIdRoute,
  AuthenticatedPitchProjectIdRoute: AuthenticatedPitchProjectIdRoute,
  AuthenticatedScenesProjectIdRoute: AuthenticatedScenesProjectIdRoute,
  AuthenticatedStoryArcProjectIdRoute: AuthenticatedStoryArcProjectIdRoute,
  AuthenticatedStoryboardProjectIdRoute: AuthenticatedStoryboardProjectIdRoute,
  AuthenticatedTablereadProjectIdRoute: AuthenticatedTablereadProjectIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  PricingRoute: PricingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
