
-- Seed Academy lessons across all 8 modules
-- Use INSERT ... ON CONFLICT to keep this idempotent (slug is unique per module via composite logic)

WITH mods AS (
  SELECT id, slug FROM public.academy_modules
)
INSERT INTO public.academy_lessons (module_id, slug, title, order_index, estimated_minutes, concept, why_it_matters, example, task_prompt, ai_button_label)
SELECT m.id, x.slug, x.title, x.order_index, x.estimated_minutes, x.concept, x.why_it_matters, x.example, x.task_prompt, x.ai_button_label
FROM (VALUES
  -- start-here (already has welcome, three-layers) → add 1 more
  ('start-here', 'studio-tour', 'Your Studio at a Glance', 3, 3,
    'SceneSmith has 8 working surfaces: Editor (the script), Scenes (the outline), Characters (the cast), Story Arc (the spine), StoryPulse (pacing), Storyboard (visuals), Table Read (hear it), Pitch (sell it).',
    'Knowing where each piece lives means you never lose work and always know what to open next.',
    'Stuck on a scene? Jump to Story Arc to see which beat you''re on — then back to Editor with fresh eyes.',
    'Open each tab in your project for 30 seconds. You don''t have to fill anything in — just see what''s there.',
    NULL),

  -- foundations (already has logline) → add 4 more
  ('foundations', 'slugline', 'Sluglines: INT, EXT, Where, When', 2, 4,
    'A slugline (scene heading) tells the reader three things: inside or outside (INT/EXT), where, and when (DAY/NIGHT). All caps. One line.',
    'Sluglines are how readers, directors, and production know what they''re looking at. Wrong slugline = wrong location, wrong crew, wrong shoot day.',
    'INT. DINER — NIGHT     |     EXT. ROOFTOP — DAWN     |     INT./EXT. CAR — CONTINUOUS',
    'Write 3 sluglines for scenes in your story. INT or EXT, location, time of day.',
    'Draft sluglines'),
  ('foundations', 'action-vs-dialogue', 'Action vs Dialogue', 3, 5,
    'Action lines describe what we SEE and HEAR. Present tense, visual, short. Dialogue is what characters say — character name centered above, line below.',
    'Beginners write thoughts and feelings ("she remembers her father"). The camera can''t film thoughts. Only what we see or hear.',
    'WRONG: "She regrets everything." | RIGHT: "She stares at the ring. Slides it off."',
    'Take one moment from your story and write it as 3-4 lines of action — visual only, no internal monologue.',
    NULL),
  ('foundations', 'page-equals-minute', 'One Page = One Minute', 4, 3,
    'Industry rule of thumb: one properly formatted screenplay page ≈ one minute of screen time. A feature is 90-120 pages. A TV half-hour is 28-32. A short is under 15.',
    'Knowing your target length tells you how much story you have room for. Most first drafts are 30% too long.',
    'Feature: 100 pages. Pilot (half-hour): 30. Pilot (hour): 55. Short: 7-12.',
    'Look at your project type. Write down your page target. That''s your finish line.',
    NULL),
  ('foundations', 'format-cheatsheet', 'The Format Cheatsheet', 5, 4,
    'Eight block types make up 99% of every screenplay: Scene Heading, Action, Character, Dialogue, Parenthetical, Transition, Shot, Note. Each has a fixed position on the page.',
    'You don''t have to memorize margins — the editor handles them. But knowing what each block is for makes you faster.',
    'Character (centered, caps) → Parenthetical (centered, lowercase, in parens) → Dialogue (centered, normal case).',
    'Open the Editor and add one of each block type. Don''t worry about content — just feel how they sit on the page.',
    NULL),

  -- story-architecture → 4 lessons
  ('story-architecture', 'three-act', 'The 3-Act Structure', 1, 6,
    'Act 1 sets up the world and forces the hero to act (25%). Act 2 is the long middle of escalating obstacles and a midpoint reversal (50%). Act 3 is the climax and resolution (25%).',
    'Every story your audience has ever loved uses this shape. Break it on purpose, never by accident.',
    'Act 1: hero refuses the call → crosses threshold. Act 2: tests, allies, midpoint, dark night. Act 3: climax, choice, new normal.',
    'Write one sentence for each act of your story. Don''t worry about beats yet — just the shape.',
    'Sketch my 3 acts'),
  ('story-architecture', 'save-the-cat-beats', 'Save the Cat: The 15 Beats', 2, 8,
    'Blake Snyder''s 15 beats: Opening Image, Theme Stated, Set-up, Catalyst, Debate, Break Into Two, B Story, Fun & Games, Midpoint, Bad Guys Close In, All Is Lost, Dark Night, Break Into Three, Finale, Final Image.',
    'When your story stalls, missing beats are usually why. The beats are diagnostic tools, not a recipe.',
    'Midpoint of Die Hard: McClane kills his first terrorist — now they know he''s there. The cat-and-mouse becomes war.',
    'Identify which beats your story already has. Note the ones you''re missing — those are your next scenes.',
    'Map my beats'),
  ('story-architecture', 'inciting-incident', 'The Inciting Incident', 3, 4,
    'The inciting incident is the event that disturbs the hero''s normal life and starts the story. Usually 10-15% in.',
    'Without an inciting incident, your hero has no reason to leave the couch. Audiences leave with them.',
    'Star Wars: Luke finds the message. The Matrix: Neo is offered the pill. Inception: Saito offers the impossible job.',
    'Name your inciting incident in one sentence. What happens that the hero can''t ignore?',
    NULL),
  ('story-architecture', 'midpoint', 'The Midpoint Shift', 4, 5,
    'The midpoint is a false win or false defeat that changes what the story is about. It reframes the stakes.',
    'A weak midpoint = a saggy Act 2. The midpoint is what keeps the second half from being more of the first half.',
    'The Godfather midpoint: Michael shoots Sollozzo. He thought he could stay out. Now he''s in.',
    'Write your midpoint in one sentence. What flips at the halfway mark?',
    NULL),

  -- character-creation → 4 lessons
  ('character-creation', 'want-vs-need', 'Want vs Need', 1, 5,
    'The WANT is what the character thinks will fix their life (external goal). The NEED is what will actually fix them (internal lesson). The arc is the journey from want to need.',
    'Characters chasing only what they want feel hollow. The need is the reason we care.',
    'Tony Stark — Want: build the suit / beat the enemy. Need: stop being his father.',
    'For your protagonist: write their WANT in one line, their NEED in one line. They should be in tension.',
    'Sharpen want vs need'),
  ('character-creation', 'character-arcs', 'The Three Character Arcs', 2, 6,
    'Positive arc: character changes for the better (most heroes). Negative arc: character refuses to change and falls (tragedies). Flat arc: character stays the same and changes the world around them (superheroes, mentors).',
    'Picking the arc shape tells you what your ending must be. Mixing them mid-story confuses the audience.',
    'Positive: Michael Corleone in Godfather is negative. Captain America is flat. Walter White is negative.',
    'Choose your protagonist''s arc type. Then write their starting belief and ending belief.',
    'Pick my arc type'),
  ('character-creation', 'archetypes', 'Archetypes Without the Cliché', 3, 5,
    'Hero, Mentor, Ally, Trickster, Threshold Guardian, Shapeshifter, Shadow, Herald. These are functions in the story, not personality types. One character can play multiple.',
    'Archetypes are casting calls — they help you see structural holes. "I have no Mentor" might be why your hero never grows.',
    'In Star Wars: Obi-Wan is Mentor + Threshold Guardian. Han is Ally + Trickster + Shapeshifter.',
    'List your main characters and tag each with 1-2 archetypes. Notice any missing roles.',
    NULL),
  ('character-creation', 'wound-lie-truth', 'Wound, Lie, Truth', 4, 6,
    'Every deep character has a Wound (something that hurt them), believes a Lie because of it ("I''m only safe alone"), and must learn a Truth ("I''m only alive when I let someone in").',
    'This is the engine of internal change. Without it, your character just reacts to plot.',
    'Wound: father left. Lie: "If I''m perfect, people stay." Truth: "Being real is what makes them stay."',
    'For your protagonist: write the wound, the lie, the truth they must learn.',
    'Find the wound, lie, truth'),

  -- scene-craft → 3 lessons
  ('scene-craft', 'scene-goal-conflict-turn', 'Goal, Conflict, Turn', 1, 5,
    'Every scene needs: a character with a GOAL, CONFLICT that blocks them, and a TURN that changes the situation (small win, small loss, or revelation).',
    'Scenes without a turn feel flat. The turn is what makes the next scene necessary.',
    'Goal: Get the truth out of him. Conflict: He lies. Turn: She realizes he''s lying TO PROTECT HER.',
    'Pick one of your scenes. Write its goal, conflict, and turn in one sentence each.',
    NULL),
  ('scene-craft', 'enter-late-leave-early', 'Enter Late, Leave Early', 2, 3,
    'Start the scene as late as possible (after greetings, after small talk). End it as early as possible (the moment the turn lands).',
    'New writers over-explain. Pros trust the audience.',
    'WRONG: She walks in, orders coffee, sits, sips, then says the line. RIGHT: "You lied." She slams the coffee down.',
    'Take any scene of yours and cut the first 3 lines and the last 3 lines. Is it stronger?',
    NULL),
  ('scene-craft', 'subtext', 'Subtext: Say One Thing, Mean Another', 3, 5,
    'Characters rarely say what they mean. Subtext is the gap between what''s said and what''s wanted. Action and silence carry meaning.',
    'On-the-nose dialogue ("I love you and I''m scared") is amateur. Subtext is the craft.',
    'She: "Is there more coffee?" (= please don''t leave). He: "I made a fresh pot." (= I''ll stay.)',
    'Take one line of on-the-nose dialogue and rewrite it as subtext.',
    'Add subtext to my scene'),

  -- dialogue → 3 lessons
  ('dialogue', 'character-voice', 'Distinct Character Voice', 1, 5,
    'Each character should sound different. Length of sentences, vocabulary, what they avoid saying, what they joke about — these are their voice fingerprints.',
    'If you can swap two characters'' lines and the scene still works, the voices aren''t distinct enough.',
    'Aaron Sorkin: long, witty, interrupting. Quentin Tarantino: looping monologues with pop-culture detours.',
    'Cover the character names in your last scene. Can you still tell who is who from voice alone?',
    NULL),
  ('dialogue', 'tags-and-action-beats', 'Action Beats Beat Dialogue Tags', 2, 4,
    'Don''t use "he said angrily." Use an action beat that shows the anger: "He sets the glass down too hard." Action beats reveal character AND control pace.',
    'Tags tell. Beats show. Beats also let the actor breathe.',
    'WRONG: "Get out," she said tearfully. RIGHT: She wipes her cheek. "Get out."',
    'Find every adverb in your dialogue ("angrily," "softly"). Replace each with an action beat.',
    NULL),
  ('dialogue', 'exposition-without-pain', 'Exposition Without Pain', 3, 5,
    'Exposition = info the audience needs. Bad: characters tell each other things they already know. Good: info comes out under pressure, mid-conflict, or as a weapon.',
    '"As you know, Bob…" is the #1 amateur tell. Make information cost something.',
    'WRONG: "As you know, we''ve been married 10 years." RIGHT: "Ten years and you still can''t load a dishwasher."',
    'Find your worst exposition dump. Rewrite it as an argument where the information slips out as ammunition.',
    'Fix my exposition'),

  -- rewriting → 2 lessons
  ('rewriting', 'first-draft-is-clay', 'The First Draft Is Clay', 1, 4,
    'Nobody writes a good first draft. The first draft exists so you have something to fix. Write fast, finish, then rewrite.',
    'Perfectionism on page 1 is why most screenplays die at page 30. Get to FADE OUT, then make it good.',
    'Hemingway: "The first draft of anything is shit." Pixar: average movie goes through 8+ full rewrites.',
    'Finish a complete pass before polishing anything. Bad pages allowed.',
    NULL),
  ('rewriting', 'the-cut-pass', 'The Cut Pass', 2, 4,
    'A focused rewrite: read your draft and cut every line that isn''t doing 2+ jobs (character + plot, plot + theme, etc.). You will lose 10-20% of pages. The script gets sharper.',
    'Length is not depth. Density is.',
    'Goal: trim 15 pages from a 110-page draft. Every scene asks: "What dies if this is gone?" If the answer is "nothing," cut it.',
    'Read your draft with one question: what can I cut? Aim for -10%.',
    NULL),

  -- pitching → 2 lessons
  ('pitching', 'logline-anatomy', 'Logline Anatomy', 1, 5,
    'A great logline has: a flawed protagonist, an inciting incident, a clear goal, stakes, and a hint of irony. 25-40 words.',
    'Industry decides whether to read your script in 5 seconds. The logline is that decision.',
    'A grieving paramedic must save the killer she''s been hunting before sunrise — or lose her last reason to live.',
    'Rewrite your logline using the 5 ingredients. Keep it under 40 words.',
    'Sharpen my logline'),
  ('pitching', 'one-page-pitch', 'The One-Page Pitch', 2, 6,
    'A one-pager: logline → main characters (1-2 lines each) → the world → the story (3 paragraphs: setup, escalation, climax) → tone & comparables ("Get Out meets Parasite").',
    'Producers read one-pagers, not 110-page scripts. The one-pager earns the read.',
    'Top of page: logline. Middle: 3 paragraphs of story. Bottom: 2-line tone statement with 2 comparable films.',
    'Draft a one-page pitch. Use the Pitch tab to generate a starting draft.',
    'Draft my one-pager')
) AS x(module_slug, slug, title, order_index, estimated_minutes, concept, why_it_matters, example, task_prompt, ai_button_label)
JOIN mods m ON m.slug = x.module_slug
WHERE NOT EXISTS (
  SELECT 1 FROM public.academy_lessons existing
  WHERE existing.module_id = m.id AND existing.slug = x.slug
);
